### PR TITLE
adds McCloyLee2015-JASA

### PR DESCRIPTION
**Pull request by drammock**
@Eric89GXL, @wronk: do we have a consensus regarding which files go here?  I somewhat arbitrarily included processed but not raw data, final but not raw audio files, and lots scripts for stimulus creation, running the experiment, data cleaning, analysis/modeling, and graphing.  Overkill?  I'm willing to prune this down if you guys think so.

### CODE REVIEW

**Comment by wronk** [comment]
I only included my main processing scripts and plotting code but not data
in any form. Of course, my data is protected by confidentiality concerns.

**Comment by larsoner** [comment]
How many MB is it?

I think it's fine to include all of these steps if you want.

**Comment by drammock** [comment]
running `du -h -s` on the local directory says 623 MB.  A lot of that is
WAV files; I tried compressing the WAV directory but GitHub complained that
the resulting file was too big.

**Comment by larsoner** [comment]
You could encode them using FLAC and it would about halve the size

**Comment by drammock** [comment]
that would break the scripts, but it's probably worth it. For that matter, just zipping the individual WAVs would do the same.  I'll do that.

**Comment by larsoner** [comment]
Can you check to see if FLAC or zip gets you a better compression ratio? Now I'm curious.

**Comment by drammock** [comment]
separate zip files for each wav (compression level 9): 109MB.  Flac with `--best` flag: 62MB

**Comment by larsoner** [comment]
nice, I'd use that then. I think it's pretty easy to encode / decode a directory full of .wav / .flac files

**Comment by drammock** [comment]
ok, all WAVs replaced with FLACs.  down to 524 MB total instead of 623 MB.  Should be ok to merge.

**Comment by larsoner** [comment]
You'll need to squash those commits so that we don't end up having 1GB+ added to the history

**Comment by drammock** [comment]
squashed.

**Comment by larsoner** [comment]
15k lines, yikes...

**Comment by larsoner** [comment]
Take that, repo!

**Comment by drammock** [comment]
thanks @Eric89GXL

**Pull request merged**
